- CRM-10971, js error fix for:
ReferenceError: optionSep is not defined
optionPart = option[1].split(optionSep);

Due to this payment processor wasn't getting reset properly.